const data = [
    {
        id: 6,
        type: 'Resource',
        date: 'April 20, 2020',
        headline: "Websites For Inspiration",
        description: "Need some inspiration for your project? With this list of 19 websites, which you can check for inspiration, you'll never run out of ideas for your website again.",
        link: "/resources/websites-for-inspiration",
        previewImage: "resources/preview_rDQNhlplI.png",
    },
    {
        id: 5,
        type: 'Resource',
        date: 'April 01, 2020',
        headline: "CSS Section Separator Generator",
        description: "A collection of customizable CSS section separators, with the possibility to easily copy the code.",
        link: "/resources/css-separator-generator",
        previewImage: "resources/css-separator-generator_7lds84DdzGW.png",
    },
    {
        id: 4,
        type: 'Resource',
        date: 'January 23, 2020',
        updatedAt: 'April 22, 2020',
        headline: "Websites For Creative Backgrounds",
        description: "A curated list of websites where you can get creative backgrounds for your websites.",
        link: "/resources/creative-backgrounds",
        previewImage: "resources/preview_gUZCcvg62.jpg",
    },
    {
        id: 3,
        type: 'Resource',
        date: 'December 29, 2019',
        headline: "Convert2Svg",
        description: "A free and open-source tool to easily transform any image or photo into a multi colored svg vector file.",
        link: "https://convert2svg.com/",
        previewImage: "resources/preview_vdfddh_Zb7zB92EJ.jpg",
    },
    {
        id: 2,
        type: 'Resource',
        date: 'December 16, 2019',
        updatedAt: 'April 10, 2020',
        headline: 'A Curated List Of Websites For Free SVG Illustrations',
        description: "Spice up your next project with beautiful illustrations from these websites.",
        link: '/resources/free-svg-illustrations',
        previewImage: 'resources/preview_C-krc8PbLyM.jpg',
    },
    {
        id: 1,
        type: 'Resource',
        date: 'November 27, 2019',
        headline: "Animated CSS Background Generator",
        description: "A collection of pure css animated backgrounds with the possibility to customize.",
        link: "/resources/animated-css-background-generator",
        previewImage: "resources/resources01_zAtYo6WzY.jpg",
    }
]

export default data
