const data = [
    {
        id: 12,
        type: 'Resource',
        date: 'January 17, 2022',
        headline: "CSS Speedrun",
        description: "A small fun app to test your CSS knowledge. Find the correct CSS selectors for the 10 puzzles as fast as possible.",
        link: "https://css-speedrun.netlify.app/",
        previewImage: "/preview/css-speedrun.png",
    },
    {
        id: 11,
        type: 'Resource',
        date: 'November 6, 2020',
        headline: "Websites For Free Icon Sets",
        description: "A curated list of websites that offer collections of free icons.",
        link: "/resources/free-icon-sets",
        previewImage: "/preview/preview_S4rXKoliGYiB.png",
    },
    {
        id: 10,
        type: 'Resource',
        date: 'July 31, 2020',
        headline: "JavaScript Object Functions Cheat Sheet",
        description: "A Cheat Sheet to quickly find all functions that can be executed on a JavaScript Object. It includes a quick explanation, the syntax and an example.",
        link: "/resources/js-object-functions-cheatsheet",
        previewImage: "/preview/js-object-cheatsheet-preview_urYtz7hxD8d.png",
    },
    {
        id: 9,
        type: 'Resource',
        date: 'July 13, 2020',
        headline: "Responsive Navigation Generator",
        description: "Quickly get the HTML and CSS for a customizable menu. It will be responsive and it turns to a burger menu on mobile, completely without JavaScript.",
        link: "/resources/navigation-generator",
        previewImage: "/preview/navigation-generator_flkQB-LbDQ-.png",
    },
    {
        id: 8,
        type: 'Resource',
        date: 'May 21, 2020',
        headline: "JavaScript Array Functions Cheat Sheet",
        description: "A Cheat Sheet to quickly find all functions that can be executed on a JavaScript Array. It includes a quick explanation, the syntax, an example, and the browser support.",
        link: "/resources/js-array-functions-cheatsheet",
        previewImage: "/preview/js-array-cheatsheet-preview_vpuXKzM9s.png",
    },
    {
        id: 7,
        type: 'Resource',
        date: 'May 04, 2020',
        headline: "Creative Hover Effects",
        description: "A collection of six creative hover effects for your inspiration. All of the effects are available on Codepen for easy copy-pasting.",
        link: "/resources/creative-hover-effects",
        previewImage: "/preview/hover-preview_eieplkIor.jpg",
    },
    {
        id: 6,
        type: 'Resource',
        date: 'April 20, 2020',
        updatedAt: 'June 05, 2020',
        headline: "Websites For Inspiration",
        description: "Need some inspiration for your project? With this list of 23 websites, which you can check for inspiration, you'll never run out of ideas for your website again.",
        link: "/resources/websites-for-inspiration",
        previewImage: "/preview/preview_rDQNhlplI.png",
    },
    {
        id: 5,
        type: 'Resource',
        date: 'April 01, 2020',
        headline: "CSS Section Separator Generator",
        description: "A collection of customizable CSS section separators, with the possibility to easily copy the code.",
        link: "/resources/css-separator-generator",
        previewImage: "/preview/css-separator-generator_7lds84DdzGW.png",
    },
    {
        id: 4,
        type: 'Resource',
        date: 'January 23, 2020',
        updatedAt: 'December 21, 2021',
        headline: "Websites For Creative Backgrounds",
        description: "A curated list of websites where you can get creative backgrounds for your websites.",
        link: "/resources/creative-backgrounds",
        previewImage: "/preview/preview_IF4o7Ga9O.jpg",
    },
    {
        id: 3,
        type: 'Resource',
        date: 'December 29, 2019',
        headline: "Convert2Svg",
        description: "A free and open-source tool to easily transform any image or photo into a multi colored svg vector file.",
        link: "https://convert2svg.com/",
        previewImage: "/preview/preview_vdfddh_Zb7zB92EJ.jpg",
    },
    {
        id: 2,
        type: 'Resource',
        date: 'December 16, 2019',
        updatedAt: 'June 05, 2020',
        headline: 'A Curated List Of Websites For Free SVG Illustrations',
        description: "Spice up your next project with beautiful illustrations from these websites.",
        link: '/resources/free-svg-illustrations',
        previewImage: '/preview/preview_C-krc8PbLyM.jpg',
    },
    {
        id: 1,
        type: 'Resource',
        date: 'November 27, 2019',
        headline: "Animated CSS Background Generator",
        description: "With this tool you can quickly create and customize animated CSS backgrounds for your website. It includes a total of three different pure CSS animated backgrounds.",
        link: "/resources/animated-css-background-generator",
        previewImage: "/preview/resources01_zAtYo6WzY.jpg",
    }
]

module.exports = data
