const data = [
    {
        id: 11,
        title: 'Web development update from 5th February 2020',
        date: 'February 5, 2020',
        link: 'https://vincentwill.com/weekly/11',
        image: '/weekly/weekly11.jpg',
        preview: '/weekly/11.jpg',
        description: "You Don't know JS Yet, Vanilla Web Projects, 24 modern ES6 code snippets and more...",
    },
    {
        id: 10,
        title: 'Web development update from 29th January 2020',
        date: 'January 29, 2020',
        link: 'https://vincentwill.com/weekly/10',
        image: '/weekly/weekly10.jpg',
        preview: '/weekly/10.jpg',
        description: 'Hoard.fyi, Screen Size Map, Mirage JS, Stock Resources, Vuer, React Libraries and more...',
    },
    {
        id: 9,
        title: 'Web development update from 22nd January 2020',
        date: 'January 22, 2020',
        link: 'https://vincentwill.com/weekly/9',
        image: '/weekly/weekly9.jpg',
        preview: '/weekly/9.jpg',
        description: 'Hero Patterns, Tiny Helpers, GoatCounter, is-website-vulnerable, JamTemplates and more...',
    },
    {
        id: 8,
        title: 'Web development update from 15th January 2020',
        date: 'January 15, 2020',
        link: 'https://wweb.dev/weekly/8',
        image: '/weekly/weekly8.jpg',
        preview: '/weekly/8.jpg',
        description: 'Gradient Magic, Broot, cacolor.co, stencils, 23 VS Code Shortcuts, Craft.js and more...',
    },
    {
        id: 7,
        title: 'Web development update from 8th January 2020',
        date: 'January 08, 2020',
        link: 'https://wweb.dev/weekly/7',
        image: '/weekly/weekly7.jpg',
        preview: '/weekly/7.jpg',
        description: 'Oh Shit, Git!?!, Colorsinspo, Parcel, Redux Style Guite, Bot Land, Rhubarb and more...',
    },
    {
        id: 6,
        title: 'Web development update from 1st January 2020',
        date: 'January 01, 2020',
        link: 'https://wweb.dev/weekly/6',
        image: '/weekly/weekly6.jpg',
        preview: '/weekly/6.jpg',
        description: 'Just JavaScript, CHL.LI, CoreUI Icons, Convert2Svg, Generative Placeholders and more...',
    },
    {
        id: 5,
        title: 'Web development update from 25th December 2019',
        date: 'December 25, 2019',
        link: 'https://wweb.dev/weekly/5',
        image: '/weekly/weekly5.jpg',
        preview: '/weekly/5.jpg',
        description: 'Codepen Most Hearted 2019, V 8.0, lazy-simon.js, GitHub Apps and more...',
    },
    {
        id: 4,
        title: 'Web development update from 18th December 2019',
        date: 'December 18, 2019',
        link: 'https://wweb.dev/weekly/4',
        image: '/weekly/weekly4.jpg',
        preview: '/weekly/4.jpg',
        description: 'Nedux, New CSS “:is()”, Challenging projects, musicForProgramming, No to Chrome and more...',
    },
    {
        id: 3,
        title: 'Web development update from 11th December 2019',
        date: 'December 11, 2019',
        link: 'https://wweb.dev/weekly/3',
        image: '/weekly/weekly3.jpg',
        preview: '/weekly/3.jpg',
        description: 'Self Hosted, CSS Layout, Refactoring UI, Deep Sea, react-spring, Leonardo and more...',
    },
    {
        id: 2,
        title: 'Web development update from 4th December 2019',
        date: 'December 04, 2019',
        link: 'https://wweb.dev/weekly/2',
        image: '/weekly/weekly2.jpg',
        preview: '/weekly/2.jpg',
        description: 'Bootstrap Icons, SVG Landscapes, roughViz.js, JavaScript Christmas, Curlie, Cell and more..',
    },
    {
        id: 1,
        title: 'Web development update from 27th November 2019',
        date: 'November 27, 2019',
        link: 'https://wweb.dev/weekly/1',
        image: '/resources/resources01.jpg',
        preview: '/weekly/1.jpg',
        description: 'SWR, Fresh Folk, Colors & fonts, Animated CSS Backgrounds, Postwoman, Pika and more',
    }
]

export default data
